"""initial schema

Revision ID: 98b47845b53a
Revises: 
Create Date: 2026-05-22 04:00:36.210200

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98b47845b53a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('agent_configs',
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_configs_agent_name'), 'agent_configs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_configs_tenant_id'), 'agent_configs', ['tenant_id'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chroma_collection', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_category'), 'knowledge_articles', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_tenant_id'), 'knowledge_articles', ['tenant_id'], unique=False)
    op.create_table('ticket_analytics_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_tickets', sa.Integer(), nullable=False),
    sa.Column('new_tickets', sa.Integer(), nullable=False),
    sa.Column('open_tickets', sa.Integer(), nullable=False),
    sa.Column('resolved_tickets', sa.Integer(), nullable=False),
    sa.Column('escalated_tickets', sa.Integer(), nullable=False),
    sa.Column('closed_tickets', sa.Integer(), nullable=False),
    sa.Column('ai_resolved_tickets', sa.Integer(), nullable=False),
    sa.Column('human_resolved_tickets', sa.Integer(), nullable=False),
    sa.Column('avg_resolution_time_hours', sa.Float(), nullable=True),
    sa.Column('avg_first_response_time_hours', sa.Float(), nullable=True),
    sa.Column('resolution_rate', sa.Float(), nullable=True),
    sa.Column('ai_resolution_rate', sa.Float(), nullable=True),
    sa.Column('avg_confidence_score', sa.Float(), nullable=True),
    sa.Column('hallucination_count', sa.Integer(), nullable=False),
    sa.Column('hallucination_rate', sa.Float(), nullable=True),
    sa.Column('avg_faithfulness_score', sa.Float(), nullable=True),
    sa.Column('avg_answer_relevancy', sa.Float(), nullable=True),
    sa.Column('total_workflow_runs', sa.Integer(), nullable=False),
    sa.Column('failed_workflow_runs', sa.Integer(), nullable=False),
    sa.Column('avg_workflow_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('pending_approvals', sa.Integer(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('avg_approval_time_minutes', sa.Float(), nullable=True),
    sa.Column('sentiment_positive', sa.Integer(), nullable=False),
    sa.Column('sentiment_neutral', sa.Integer(), nullable=False),
    sa.Column('sentiment_negative', sa.Integer(), nullable=False),
    sa.Column('sentiment_angry', sa.Integer(), nullable=False),
    sa.Column('category_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'snapshot_date', name='uq_analytics_tenant_date')
    )
    op.create_index('ix_analytics_tenant_date', 'ticket_analytics_snapshots', ['tenant_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_ticket_analytics_snapshots_snapshot_date'), 'ticket_analytics_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_ticket_analytics_snapshots_tenant_id'), 'ticket_analytics_snapshots', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'AGENT', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_tenant_active', 'users', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_tenant_action', 'audit_logs', ['tenant_id', 'action'], unique=False)
    op.create_index('ix_audit_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_tenant_resource', 'audit_logs', ['tenant_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('tickets',
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'AWAITING_CUSTOMER', 'RESOLVED', 'ESCALATED', 'CLOSED', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Enum('DASHBOARD', 'EMAIL', 'API', 'SLACK', 'WEBHOOK', name='ticket_source'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('ai_category', sa.String(length=100), nullable=True),
    sa.Column('ai_sentiment', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assigned_to'), 'tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tickets_category'), 'tickets', ['category'], unique=False)
    op.create_index(op.f('ix_tickets_deleted_at'), 'tickets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tickets_external_id'), 'tickets', ['external_id'], unique=True)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index('ix_tickets_tenant_assigned', 'tickets', ['tenant_id', 'assigned_to'], unique=False)
    op.create_index('ix_tickets_tenant_category', 'tickets', ['tenant_id', 'category'], unique=False)
    op.create_index('ix_tickets_tenant_created', 'tickets', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.create_index('ix_tickets_tenant_priority', 'tickets', ['tenant_id', 'priority'], unique=False)
    op.create_index('ix_tickets_tenant_status', 'tickets', ['tenant_id', 'status'], unique=False)
    op.create_table('conversations',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ESCALATED', 'AWAITING_APPROVAL', name='conversation_status'), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_tenant_created', 'conversations', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_index('ix_conversations_tenant_status', 'conversations', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_conversations_tenant_ticket', 'conversations', ['tenant_id', 'ticket_id'], unique=False)
    op.create_index(op.f('ix_conversations_ticket_id'), 'conversations', ['ticket_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'AI_AGENT', 'HUMAN_AGENT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('langsmith_run_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_conv_role', 'messages', ['conversation_id', 'role'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ESCALATED', 'CANCELLED', name='workflow_run_status'), nullable=False),
    sa.Column('langsmith_run_id', sa.String(length=255), nullable=True),
    sa.Column('langsmith_trace_url', sa.String(length=500), nullable=True),
    sa.Column('input_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nodes_visited', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('resolution_source', sa.String(length=50), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_conversation_id'), 'workflow_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_langsmith_run_id'), 'workflow_runs', ['langsmith_run_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_tenant_id'), 'workflow_runs', ['tenant_id'], unique=False)
    op.create_index('ix_workflow_runs_tenant_started', 'workflow_runs', ['tenant_id', 'started_at'], unique=False)
    op.create_index('ix_workflow_runs_tenant_status', 'workflow_runs', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_workflow_runs_tenant_ticket', 'workflow_runs', ['tenant_id', 'ticket_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_ticket_id'), 'workflow_runs', ['ticket_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'MODIFIED', 'EXPIRED', name='approval_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='approval_priority'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('proposed_response', sa.Text(), nullable=False),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_assigned_to'), 'approval_requests', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_approval_requests_expires_at'), 'approval_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_requested_at'), 'approval_requests', ['requested_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_approval_requests_tenant_id'), 'approval_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_ticket_id'), 'approval_requests', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_workflow_run_id'), 'approval_requests', ['workflow_run_id'], unique=False)
    op.create_index('ix_approvals_tenant_assigned', 'approval_requests', ['tenant_id', 'assigned_to'], unique=False)
    op.create_index('ix_approvals_tenant_requested', 'approval_requests', ['tenant_id', 'requested_at'], unique=False)
    op.create_index('ix_approvals_tenant_status', 'approval_requests', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_approvals_ticket', 'approval_requests', ['ticket_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('eval_type', sa.Enum('RAGAS', 'CUSTOM', 'MANUAL', name='eval_type'), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('answer_relevancy', sa.Float(), nullable=True),
    sa.Column('context_precision', sa.Float(), nullable=True),
    sa.Column('context_recall', sa.Float(), nullable=True),
    sa.Column('dataset_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('langsmith_dataset_id', sa.String(length=255), nullable=True),
    sa.Column('langsmith_experiment_id', sa.String(length=255), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluations_conversation', 'evaluations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_evaluations_conversation_id'), 'evaluations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_evaluations_eval_type'), 'evaluations', ['eval_type'], unique=False)
    op.create_index('ix_evaluations_tenant_date', 'evaluations', ['tenant_id', 'evaluated_at'], unique=False)
    op.create_index(op.f('ix_evaluations_tenant_id'), 'evaluations', ['tenant_id'], unique=False)
    op.create_index('ix_evaluations_tenant_type', 'evaluations', ['tenant_id', 'eval_type'], unique=False)
    op.create_index(op.f('ix_evaluations_workflow_run_id'), 'evaluations', ['workflow_run_id'], unique=False)
    op.create_table('hallucination_flags',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='hallucination_severity'), nullable=False),
    sa.Column('flagged_claim', sa.Text(), nullable=False),
    sa.Column('detection_method', sa.String(length=100), nullable=False),
    sa.Column('faithfulness_score', sa.Float(), nullable=True),
    sa.Column('evidence_checked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detection_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hall_flags_message', 'hallucination_flags', ['message_id'], unique=False)
    op.create_index('ix_hall_flags_run', 'hallucination_flags', ['workflow_run_id'], unique=False)
    op.create_index('ix_hall_flags_tenant_flagged', 'hallucination_flags', ['tenant_id', 'flagged_at'], unique=False)
    op.create_index(op.f('ix_hallucination_flags_message_id'), 'hallucination_flags', ['message_id'], unique=False)
    op.create_index(op.f('ix_hallucination_flags_severity'), 'hallucination_flags', ['severity'], unique=False)
    op.create_index(op.f('ix_hallucination_flags_tenant_id'), 'hallucination_flags', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_hallucination_flags_workflow_run_id'), 'hallucination_flags', ['workflow_run_id'], unique=False)
    op.create_table('workflow_node_executions',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SKIPPED', 'RUNNING', 'COMPLETED', 'FAILED', name='node_status'), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_node_exec_run_node', 'workflow_node_executions', ['workflow_run_id', 'node_name'], unique=False)
    op.create_index('ix_node_exec_run_sequence', 'workflow_node_executions', ['workflow_run_id', 'sequence_order'], unique=False)
    op.create_index(op.f('ix_workflow_node_executions_node_name'), 'workflow_node_executions', ['node_name'], unique=False)
    op.create_index(op.f('ix_workflow_node_executions_workflow_run_id'), 'workflow_node_executions', ['workflow_run_id'], unique=False)
    op.create_table('confidence_scores',
    sa.Column('node_execution_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('generation_score', sa.Float(), nullable=True),
    sa.Column('relevancy_score', sa.Float(), nullable=True),
    sa.Column('faithfulness_score', sa.Float(), nullable=True),
    sa.Column('is_below_threshold', sa.Boolean(), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('score_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_execution_id'], ['workflow_node_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conf_scores_message', 'confidence_scores', ['message_id'], unique=False)
    op.create_index('ix_conf_scores_node_exec', 'confidence_scores', ['node_execution_id'], unique=False)
    op.create_index(op.f('ix_confidence_scores_message_id'), 'confidence_scores', ['message_id'], unique=False)
    op.create_index(op.f('ix_confidence_scores_node_execution_id'), 'confidence_scores', ['node_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confidence_scores_node_execution_id'), table_name='confidence_scores')
    op.drop_index(op.f('ix_confidence_scores_message_id'), table_name='confidence_scores')
    op.drop_index('ix_conf_scores_node_exec', table_name='confidence_scores')
    op.drop_index('ix_conf_scores_message', table_name='confidence_scores')
    op.drop_table('confidence_scores')
    op.drop_index(op.f('ix_workflow_node_executions_workflow_run_id'), table_name='workflow_node_executions')
    op.drop_index(op.f('ix_workflow_node_executions_node_name'), table_name='workflow_node_executions')
    op.drop_index('ix_node_exec_run_sequence', table_name='workflow_node_executions')
    op.drop_index('ix_node_exec_run_node', table_name='workflow_node_executions')
    op.drop_table('workflow_node_executions')
    op.drop_index(op.f('ix_hallucination_flags_workflow_run_id'), table_name='hallucination_flags')
    op.drop_index(op.f('ix_hallucination_flags_tenant_id'), table_name='hallucination_flags')
    op.drop_index(op.f('ix_hallucination_flags_severity'), table_name='hallucination_flags')
    op.drop_index(op.f('ix_hallucination_flags_message_id'), table_name='hallucination_flags')
    op.drop_index('ix_hall_flags_tenant_flagged', table_name='hallucination_flags')
    op.drop_index('ix_hall_flags_run', table_name='hallucination_flags')
    op.drop_index('ix_hall_flags_message', table_name='hallucination_flags')
    op.drop_table('hallucination_flags')
    op.drop_index(op.f('ix_evaluations_workflow_run_id'), table_name='evaluations')
    op.drop_index('ix_evaluations_tenant_type', table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_tenant_id'), table_name='evaluations')
    op.drop_index('ix_evaluations_tenant_date', table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_eval_type'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_conversation_id'), table_name='evaluations')
    op.drop_index('ix_evaluations_conversation', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('ix_approvals_ticket', table_name='approval_requests')
    op.drop_index('ix_approvals_tenant_status', table_name='approval_requests')
    op.drop_index('ix_approvals_tenant_requested', table_name='approval_requests')
    op.drop_index('ix_approvals_tenant_assigned', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_workflow_run_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_ticket_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_tenant_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requested_at'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_expires_at'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_assigned_to'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_workflow_runs_ticket_id'), table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_tenant_ticket', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_tenant_status', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_tenant_started', table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_tenant_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_langsmith_run_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_conversation_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conv_role', table_name='messages')
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_ticket_id'), table_name='conversations')
    op.drop_index('ix_conversations_tenant_ticket', table_name='conversations')
    op.drop_index('ix_conversations_tenant_status', table_name='conversations')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index('ix_conversations_tenant_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_tickets_tenant_status', table_name='tickets')
    op.drop_index('ix_tickets_tenant_priority', table_name='tickets')
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.drop_index('ix_tickets_tenant_created', table_name='tickets')
    op.drop_index('ix_tickets_tenant_category', table_name='tickets')
    op.drop_index('ix_tickets_tenant_assigned', table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_external_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_deleted_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_audit_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_tenant_resource', table_name='audit_logs')
    op.drop_index('ix_audit_tenant_created', table_name='audit_logs')
    op.drop_index('ix_audit_tenant_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_tenant_role', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('ix_users_tenant_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ticket_analytics_snapshots_tenant_id'), table_name='ticket_analytics_snapshots')
    op.drop_index(op.f('ix_ticket_analytics_snapshots_snapshot_date'), table_name='ticket_analytics_snapshots')
    op.drop_index('ix_analytics_tenant_date', table_name='ticket_analytics_snapshots')
    op.drop_table('ticket_analytics_snapshots')
    op.drop_index(op.f('ix_knowledge_articles_tenant_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_category'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_agent_configs_tenant_id'), table_name='agent_configs')
    op.drop_index(op.f('ix_agent_configs_agent_name'), table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
